### PR TITLE
Support for ingress

### PR DESCRIPTION
**Pull request by olymk2**
new pr for #78 rebased, what needs doing in this pr to get it merged, i can see something about long names in the old pr i could not reproduce this is it fixed ?

### CODE REVIEW

**Comment by noorul** [comment]
ingress-output

**Comment by noorul** [comment]
I see that output when I test this patch.

**Comment by olymk2** [comment]
okay i will see if i can adjust, can you grab some example values, or add them to the test json file, looks like its only a few fields that are required to display that row.

**Comment by olymk2** [comment]
did you blank out the names ? tried this on 2 kubernetes clusters and i get nothing like that screen shot :/

**Comment by olymk2** [comment]
is that actually an ipv6 address in your screenshot ?

**Comment by olymk2** [comment]
I just got this output, the ip addresses in this situation display as in your screen shot, so assuming its the same situation for you i will try and resolve that.

> NAME            HOSTS                    ADDRESS                              PORTS     AGE
> lkube-ingress   example   1.1.1.1,2.2.2.2,3.3.3.3   80, 443   23d

**Comment by noorul** [comment]
Also I have ingress configured with hosts empty. It might be the cause. Can you try to add some ingress without host?

**Comment by olymk2** [comment]
yeah I, will be updating I made a commit with some json that failed when viewed so i can work with it will let you know when its in a good state.

**Comment by olymk2** [comment]
Okay see how you get on with this one, I think the cause was json in this format.
```
                    "ingress": [
                        {
                            "ip": "3.10.144.54"
                        },
                        {
                            "ip": "3.10.151.11"
                        },
                        {
                            "ip": "3.9.177.209"
                        }
                    ]
```

all the working examples only had a single result

**Comment by olymk2** [comment]
@noorul can we get the buidl fixed, dont think its an issue with this pr then we can merge this feature :)

**Comment by noorul** [comment]
@olymk2 Done! Can you re-base?

**Comment by olymk2** [comment]
@noorul rebased but the undo tree error came back :(

**Comment by noorul** [comment]
@olymk2  I think it is random failure. But I am still getting the same output :(

**Comment by noorul** [comment]
I will merge this and maybe, I will try whether I can fix what I am seeing.

**Comment by olymk2** [comment]
okay cheers, thanks for that :)

**Pull request merged**
