### PR TITLE
Statefulset

### PR DESCRIPTION
**Pull request by olymk2**

### CODE REVIEW

**Comment by olymk2** [comment]
as @iocanel seems happy for the PRs to be rebased I have done just that.
Done nothing more than rebase and re raise in the hope we can get it merged.
I assume it should be fairly safe as its a separate view.
https://github.com/chrisbarrett/kubernetes-el/pull/80

**Comment by olymk2** [comment]
@noorul can we merge this or does something else need doing ?

**Comment by noorul** [comment]
@olymk2 Looks like tests are failing.

**Comment by olymk2** [comment]
I did see that, but this is a case of a general issue not an issue with the code from what I can tell.

```
Package operations: 9 installs, 0 removals

  - Installing [ 1/9] magit-popup (2.13.0)... downloading  - Installing [ 1/9] magit-popup (2.13.0)... done

  - Installing [ 2/9] magit (2.8.0)... downloading  - Installing [ 2/9] magit (2.8.0)... done

  - Installing [ 3/9] dash (2.12.0)... already present

  - Installing [ 4/9] emacs (25.1)... already present

  - Installing [ 5/9] f (latest)... downloading  - Installing [ 5/9] f (latest)... done

  - Installing [ 6/9] ert-runner (latest)... downloading  - Installing [ 6/9] ert-runner (latest)... done

  - Installing [ 7/9] noflet (latest)... downloading  - Installing [ 7/9] noflet (latest)... done

  - Installing [ 8/9] evil (latest)... downloadingDependency evil failed to install: Package ‘undo-tree-0.6.3’ is unavailable

Output:

nil

The command "cask install" failed and exited with 255 during .
```

seems its trying to install packages in particular undo-tree which seems strange to install for tests, not familiar with travis can we just remove this package and is it easy todo ? or am i missing something all together ?

**Comment by noorul** [comment]
@olymk2  Can you re-base?

**Comment by olymk2** [comment]
I can indeed, I just did a rebase from origin/master and it did not have any changes pushed up to my branch again anyway just in case.
looking at git log looks like the last commit exists in this branch so it should be good ?

**Comment by noorul** [comment]
Can you rebase?

**Comment by olymk2** [comment]
rebased,

` Installing [ 8/9] evil (latest)... downloadingDependency evil failed to install: https://elpa.gnu.org/packages/undo-tree-0.6.5.el: Bad Request`

unfortunately same issue with undo tree, why is undo tree even needed for evil :(

**Comment by noorul** [comment]
It is working for me. See this test PR https://github.com/chrisbarrett/kubernetes-el/pull/108

**Comment by noorul** [comment]
I think tests are missing

**Comment by olymk2** [comment]
yay finally, everything passes :)

**Comment by olymk2** [comment]
@noorul I have added tests as a seperate commit based on the deployment tests, hopefully good to merge now ?

**Comment by noorul** [comment]
@olymk2 Will test this locally and let you know.

**Comment by olymk2** [comment]
great when its merged, I may have a stab at bringing the ingress pr up to scratch so that can get merged.

**Comment by olymk2** [comment]
awesome thanks :)

**Pull request merged**
